// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olfallmilzgigdotfxuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZmFsbG1pbHpnaWdkb3RmeHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDk5MTcsImV4cCI6MjA2MTI4NTkxN30.yNIKyBVfvuwRv3UfTnx4C5dVxWLuKDxn_huFiiH9Y6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);